title: Elon Musk a jeho Společnosti
baseURL: https://naughty-swartz-0d6ba4.netlify.com/
languageCode: cs-cz
publishDir: public

menu:
  main:
    - name: Elon Musk a jeho cesta
      url: /
      weight: 10
    - name: Archive
      identifier: post
      url: /post/
      weight: 20

params:
  description: Description of my new site.
  authors: Authors

